### ISSUE TITLE
Error: No Discrete Choice function set in NA, NA

### ISSUE THREAD

**Issue by Peilin-mumu** [umd-cgs/gcam-china#3]
I’ve been testing the default scenarios to verify that everything works correctly. When using the default configuration.xml, all models solve without issues. However, when I switch to using configuration_ssp.xml, I encounter the following error: “Error: No Discrete Choice function set in NA, NA” (please see the attached main log). I’ve attempted several solutions to resolve this, but none have been successful so far. Does anyone know what could be causing this issue and how to fix it?

**Comment by Peilin-mumu** [comment]
[main_log.txt](https://github.com/user-attachments/files/17904360/main_log.txt)

**Comment by JiahongGUO121** [comment]
https://github.com/umd-cgs/gcam-china/issues/1
https://github.com/JGCRI/gcam-core/issues/180
please see the above URLs
